name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间16:00运行(北京时间午夜12点)
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 升级权限以支持发布操作

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: Dev  # 确保分支存在，否则改为 main

    - name: Debug Git Status
      run: |
        echo "Current Branch: $(git branch --show-current)"
        git branch -a
        git rev-parse HEAD

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get current datetime
      id: datetime
      run: echo "datetime=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly-${{ steps.datetime.outputs.datetime }}
        name: Nightly ${{ steps.datetime.outputs.datetime | replace('_', ' ') }}
        body: |
          ⚡ 自动构建的夜间版本
          - 构建时间: ${{ steps.datetime.outputs.datetime }}
          - 源码版本: ${{ github.sha }}
        prerelease: true
        draft: false
        files: |
          src/BBdownEasy.sh
          src/bbdownInstall.sh
          src/bbdownInstall.bat
          src/BBdownEasy.bat
